backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'Type', name: 'type', widget: 'string', required: false }
      - {
          label: 'Language',
          name: 'language',
          widget: 'string',
          required: false,
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: Summary 80-150,
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{80,150}', 'Must be within 80 and 150 characters'],
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
          date_format: 'DD.MM.YYYY',
          format: 'LL',
        }
      - {
          label: 'Updated Date',
          name: 'update',
          widget: 'datetime',
          required: false,
          date_format: 'DD.MM.YYYY',
          format: 'LL',
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - {
          label: 'Author Link',
          name: 'authorlink',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'coding'
    label: 'Coding'
    folder: 'content/coding'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'Type', name: 'type', widget: 'string', required: false }
      - {
          label: 'Language',
          name: 'language',
          widget: 'string',
          required: false,
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: Summary 80-150,
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{80,150}', 'Must be within 80 and 150 characters'],
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
          date_format: 'DD.MM.YYYY',
          format: 'LL',
        }
      - {
          label: 'Updated Date',
          name: 'update',
          widget: 'datetime',
          required: false,
          date_format: 'DD.MM.YYYY',
          format: 'LL',
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - {
          label: 'Author Link',
          name: 'authorlink',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
